# Unique name for this workflow
name: CI

# Definition when the workflow should run
on:
  workflow_dispatch:
  pull_request:
    types: [edited, opened, synchronize, reopened, review_requested]
  push:
    #branches:
    #  - main
    paths:
      - "force-app/**"
      - "sample-handler/**"
      - "sfdx-project.json"
      - "package-lock.json"

# Jobs to be executed
jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code
      - name: "Checkout source code"
        uses: actions/checkout@v3

      # Cache node_modules to speed up the process
      - name: "Restore node_modules cache"
        id: cache-npm
        uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ env.cache-name }}-
            npm-
      # Install npm dependencies for Prettier and Jest
      - name: "Install npm dependencies"
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      # Start local Apex parser server for Prettier
      - name: "Start local Apex parser server for Prettier"
        run: npm run apex:local:start &

      # Wait for Apex parser server startup
      - name: "Wait for Apex parser server startup"
        run: timeout 30 bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/$0/$1; do sleep 1; done' 127.0.0.1 2117

      # Prettier Apex formatting
      - name: "Code formatting EXECUTION with Prettier"
        run: npm run prettier:apex:local

      # Prettier format check
      - name: "Code formatting verification with Prettier"
        run: npm run prettier:verify

      # Stop local Apex parser server for Prettier
      - name: "Stop local Apex parser server for Prettier"
        if: always()
        run: npm run apex:local:stop
  pmd-analysis:
    runs-on: ubuntu-latest
    #needs: format-lint-apex-lwc
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      # Checkout the source code
      - name: "Checkout source code"
        uses: actions/checkout@v3

      # Install PMD
      - name: "Install PMD"
        run: |
          PMD_VERSION=`cat pmd/pmd-version.txt`
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F$PMD_VERSION/pmd-bin-$PMD_VERSION.zip
          unzip pmd-bin-$PMD_VERSION.zip -d ~
          mv ~/pmd-bin-$PMD_VERSION ~/pmd
          ~/pmd/bin/run.sh pmd --version
      # Run PMD scan
      - name: "Run PMD scan"
        run: ~/pmd/bin/run.sh pmd -d force-app -d sample-handler --rulesets pmd/ruleset.xml --format csv --no-cache -min 2 --verbose -r pmd/pmd.csv
